# Generated by Django 4.0.4 on 2022-05-19 12:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctioneer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Ivan', max_length=50)),
                ('surname', models.CharField(default='Ivanov', max_length=50)),
                ('patronymic', models.CharField(default='Ivanovich', max_length=50, null=True)),
                ('password', models.CharField(default=' ', max_length=50)),
                ('email', models.EmailField(default='owner@mail.com', max_length=254)),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Slot', max_length=50)),
                ('description', models.CharField(default='Description', max_length=200, null=True)),
                ('start_price', models.FloatField(default=0)),
                ('end_price', models.FloatField(default=models.FloatField(default=0))),
                ('auctioneer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_1.auctioneer')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo', models.ImageField(null=True, upload_to='img')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_1.slot')),
            ],
        ),
    ]
