# Generated by Django 3.2.12 on 2022-05-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tester',
        ),
    ]
