# Generated by Django 4.0.4 on 2022-05-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_price',
            field=models.FloatField(null=True),
        ),
    ]
