# Generated by Django 3.2.12 on 2022-05-16 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0002_delete_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctioneer',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='auctioneer',
            name='email',
            field=models.EmailField(default='owner@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='auctioneer',
            name='password',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='auctioneer',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, default='+12223334444', max_length=31),
        ),
        migrations.AlterField(
            model_name='auctioneer',
            name='name',
            field=models.CharField(default='Ivan', max_length=50),
        ),
        migrations.AlterField(
            model_name='auctioneer',
            name='surname',
            field=models.CharField(default='Ivanov', max_length=50),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Slot', max_length=50)),
                ('description', models.CharField(default='Description', max_length=200, null=True)),
                ('start_price', models.FloatField(default=0)),
                ('end_price', models.FloatField(default=models.FloatField(default=0))),
                ('auctioneer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_1.auctioneer')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo', models.ImageField(null=True, upload_to='img')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_1.slot')),
            ],
        ),
    ]
