# Generated by Django 4.0.4 on 2022-05-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Auctioneer',
        ),
    ]
