# Generated by Django 4.0.4 on 2022-04-18 14:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('kind', models.CharField(max_length=200)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('landing_day', models.DateField(default=datetime.datetime(2022, 4, 18, 14, 19, 22, 934317, tzinfo=utc))),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('max_weight_fruit_on_tree', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Garden.tree')),
            ],
        ),
    ]
