# Generated by Django 4.0.4 on 2022-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='landing_day',
            field=models.DateField(),
        ),
    ]
