# Generated by Django 4.0.4 on 2022-05-04 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Garden', '0004_remove_tree_id_tree_height_tree_index_tree_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='landing_day',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 13, 8, 26, 126939, tzinfo=utc), null=True),
        ),
    ]
