# Generated by Django 4.0.4 on 2022-05-04 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Garden', '0005_alter_tree_landing_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='landing_day',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 16, 52, 19, 120239, tzinfo=utc), null=True),
        ),
    ]
