# Generated by Django 4.0.4 on 2022-05-04 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Garden', '0006_alter_tree_landing_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='tree',
            name='landing_day',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
