# Generated by Django 4.0.4 on 2022-05-04 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Garden', '0002_alter_tree_landing_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='height',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='index',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='landing_day',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='max_weight_fruit_on_tree',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='width',
        ),
        migrations.AddField(
            model_name='tree',
            name='id',
            field=models.BigAutoField(auto_created=True, default=datetime.datetime(2022, 5, 4, 12, 46, 5, 692833, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fruit',
            name='tree',
            field=models.ForeignKey(default='Some String', null=True, on_delete=django.db.models.deletion.CASCADE, to='Garden.tree'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='weight',
            field=models.FloatField(default=0, null=True),
        ),
    ]
