# Generated by Django 4.0.4 on 2022-05-04 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Garden', '0003_remove_tree_height_remove_tree_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='id',
        ),
        migrations.AddField(
            model_name='tree',
            name='height',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='index',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tree',
            name='kind',
            field=models.CharField(default='Some String', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='landing_day',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 12, 53, 58, 899592, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='max_weight_fruit_on_tree',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='width',
            field=models.FloatField(default=0, null=True),
        ),
    ]
